export const BACKEND_API_URL = process.env.REACT_APP_BACKEND_API_URL;
export const FRONTEND_API_URL = process.env.REACT_APP_FRONTEND_API_URL;
export const ADMIN_USERNAME = process.env.REACT_APP_ADMIN_USERNAME;
export const ALLOWED_EMAIL_SUFFIXES = process.env.REACT_APP_ALLOWED_EMAIL_SUFFIXES.split(",")